- name: configuring mongodb server
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repo.d/mongo.repo

  - name: Install mongodb server
    ansibile.builtin.dnf:
      name: mongodb-org
      state: present
    
  - name: start and enable mongodb
    ansible.builtin.service:
      name: mongod
      state: started

  - name: allow remote connections
    ansible.builin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: restart mongodb
    ansible.builtin.service:
      name: mongod
      state: restarted
